services:
  frontend:
    image: node:24.11.1-alpine
    working_dir: /app
    command: ["sh", "-c", "npm install && npm run dev -- --hostname 0.0.0.0 --port 3000"]
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ../../pmd_frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      api:
        condition: service_healthy
    networks:
      - pmd_dev
    restart: unless-stopped
    init: true
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://127.0.0.1:3000', res => { process.exit(res.statusCode && res.statusCode < 500 ? 0 : 1); }).on('error', () => process.exit(1));"
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s

  api:
    build:
      context: ../../pmd
      dockerfile: ../pmd_infra/docker/backend/Dockerfile.api
    env_file:
      - ../.env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    volumes:
      - ../../pmd:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pmd_dev
    restart: unless-stopped
    init: true
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=2).read()"
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  worker:
    build:
      context: ../../pmd
      dockerfile: ../pmd_infra/docker/backend/Dockerfile.worker
    env_file:
      - ../.env
    command: ["python", "-m", "app.jobs.worker"]
    volumes:
      - ../../pmd:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pmd_dev
    restart: unless-stopped
    init: true
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import os; from redis import Redis; url=os.environ.get('REDIS_URL'); assert url; Redis.from_url(url).ping(); assert os.environ.get('DATABASE_URL')"
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  scheduler:
    build:
      context: ../../pmd
      dockerfile: ../pmd_infra/docker/backend/Dockerfile.scheduler
    env_file:
      - ../.env
    command: ["python", "-m", "app.jobs.scheduler"]
    volumes:
      - ../../pmd:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pmd_dev
    restart: unless-stopped
    init: true
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import os; from redis import Redis; url=os.environ.get('REDIS_URL'); assert url; Redis.from_url(url).ping(); assert os.environ.get('DATABASE_URL')"
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:16
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - pmd_dev
    restart: unless-stopped

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - pmd_dev
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  frontend_node_modules:

networks:
  pmd_dev:
    driver: bridge
